spring:
  application:
    name: spring-service01
  profiles:
    active: dev
server:
  port: 8086
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/
  instance:
    instance-id: ${spring.application.name}:${server.port}
    # 发呆时间，即服务续约到期时间（缺省为90s）
    lease-expiration-duration-in-seconds: 90
    # 心跳时间，即服务续约间隔时间（缺省为30s）
    lease-renewal-interval-in-seconds: 30
    # 设置微服务调用地址为IP优先（缺省为false）
    prefer-ip-address: false

feign:
  sentinel:
    enabled: true

logging:
  level:
    com.example.sentinel.SentinelSerivceDemo: debug

ribbon:
  eager-load:
    enabled: false
